server:
  port: "${SERVICE_PORT}"

spring:
  application:
    name: products

  datasource:
    url: "${DB_URL}"
    driverClassName: com.mysql.cj.jdbc.Driver
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate

  services:
    products-service:
      url: "http://products-service:${SERVICE_PORT}"