server:
  port: ""

spring:
  application:
    name: authentication

  datasource:
    url: ""
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ""
    password: ""

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate

  email-configuration:
    host: smtp.gmail.com
    port: 587
    auth: true
    enableTLS: true
    senderEmail: ""
    senderPassword: ""