server:
  port: "${SERVICE_PORT}"

spring:
  application:
    name: authentication

  datasource:
    url: "${DB_URL}"
    driverClassName: com.mysql.cj.jdbc.Driver
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate

  email-configuration:
    host: smtp.gmail.com
    port: 587
    auth: true
    enableTLS: true
    senderEmail: "${EMAIL_ADDRESS}"
    senderPassword: "${EMAIL_PASSWORD}"

  services:
    user-management-service:
      url: "http://user-management-service:8081"