server:
  port: 8082

spring:
  application:
    name: products

  datasource:
    url: ""
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ""
    password: ""

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate