CREATE TABLE IF NOT EXISTS tb_email_verification(
    EMAIL_ADDRESS             VARCHAR(100)     NOT NULL,
    VERIFICATION_OTP_CODE     INTEGER          NOT NULL,
    REQUEST_TIMESTAMP         DATETIME(6)      NOT NULL,
    PRIMARY KEY (EMAIL_ADDRESS)
);