CREATE TABLE IF NOT EXISTS tb_product (
  ID                 BIGINT        NOT NULL AUTO_INCREMENT,
  NAME               VARCHAR(50)   NOT NULL,
  SLUG               VARCHAR(50)   NOT NULL,
  DESCRIPTION        VARCHAR(255)  NOT NULL,
  CATEGORY_SLUG      VARCHAR(50)   NOT NULL,
  PRICE              DECIMAL(13,2) NOT NULL DEFAULT 0.00,
  CURRENCY           VARCHAR(3)    NOT NULL,
  STOCK_AVAILABLE    INT           NOT NULL DEFAULT 0,
  IS_AVAILABLE       TINYINT(1)    NOT NULL DEFAULT 1,
  CREATED_AT         DATETIME(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  UPDATED_AT         DATETIME(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (ID)
);