CREATE TABLE IF NOT EXISTS tb_users (
  EMAIL_ADDRESS   VARCHAR(100)      NOT NULL,
  FIRST_NAME      VARCHAR(50)       NOT NULL,
  LAST_NAME       VARCHAR(100)      NOT NULL,
  COUNTRY_CODE    VARCHAR(2)        NOT NULL,
  MOBILE_NUMBER   VARCHAR(15)       NOT NULL,
  HOME_ADDRESS    VARCHAR(255)      NOT NULL,
  DATE_OF_BIRTH   DATE              NOT NULL,
  CREATED_AT      DATETIME(6)       NOT NULL,
  UPDATED_AT      DATETIME(6)       NOT NULL,
  PRIMARY KEY (EMAIL_ADDRESS)
);