server:
  port: "${SERVICE_GATEWAY_PORT}"

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: authentication-service
          uri: http://authentication-service:${SERVICE_AUTH_PORT}
          predicates:
            - Path=/api/auth/**
        - id: user-management-service
          uri: http://user-management-service:${SERVICE_USER_MANAGEMENT_PORT}
          predicates:
            - Path=/api/users/**
        - id: products-service
          uri: http://products-service:${SERVICE_PRODUCTS_PORT}
          predicates:
            - Path=/api/products/**, /api/categories/**, /api/discounts/**