apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: nicomesa/api-gateway:latest
          volumeMounts:
            - name: config-volume
              mountPath: /config
              readOnly: true
          env:
            - name: SPRING_CONFIG_LOCATION
              value: /config/application.yaml
      volumes:
        - name: config-volume
          configMap:
            name: api-gateway-template